const AtlasLocalization = {
    "__L_SEARCH__": "Buscar script...",
    "__L_L0__": "L0: Contratos",
    "__L_L1__": "L1: Datos/DNA",
    "__L_L2__": "L2: Sistemas Core",
    "__L_L3__": "L3: Lógica",
    "__L_L4__": "L4: Interfaz UI",
    "__L_DETAIL_TITLE__": "Detalle del script",
    "__L_RESET__": "Restablecer vista",
    "__L_SELECT_NODE__": "Selecciona un nodo para ver el análisis de impacto y telemetría.",
    "__L_STRATEGIC__": "DESCRIPCIÓN ESTRATÉGICA",
    "__L_IMPACT__": "ANÁLISIS DE IMPACTO (SUPERIORES)",
    "__L_SCENE__": "PRESENCIA EN ESCENA / JERARQUÍA",
    "__L_DEPS__": "DEPENDENCIAS (LECTURAS)",
    "__L_SOURCE__": "CÓDIGO FUENTE COMPLETO",
    "__L_HELP_BTN__": "Centro de ayuda",
    "__L_REFRESH_BTN__": "Actualizar datos",
    "__L_TAB_ARCH__": "Arquitectura",
    "__L_TAB_INTEG__": "Integridad",
    "__L_TAB_AI__": "Suite IA",
    "__L_TELEMETRY_OVERVIEW__": "PANORAMA DE TELEMETRÍA DEL PROYECTO",
    "__L_CRITICAL_MODS__": "MÓDULOS CRÍTICOS (DEFCON 3)",
    "__L_FRAGILE_MODS__": "MÓDULOS FRÁGILES (DEFCON 2)",
    "__L_GOD_DETECTED__": "GOD OBJECTS DETECTADOS",
    "__L_TECH_DEBT__": "DEUDA TÉCNICA (TODO/FIXME)",
    "__L_INTEGRITY_STATUS__": "ESTADO DE INTEGRIDAD",
    "__L_DEFCON_1__": "ESTABLE (DEFCON 1)",
    "__L_DEFCON_2__": "FRÁGIL (DEFCON 2)",
    "__L_DEFCON_3__": "CRÍTICO (DEFCON 3)",
    "__L_GOD_WARN__": "⚠️ AVISO ARQUITECTÓNICO: SISTEMA GOD OBJECT DETECTADO",
    "__L_HEAVY_WARN__": "⚡ AVISO DE RENDIMIENTO: BUCLES PESADOS ENCONTRADOS",
    "__L_WORKFLOW_CONTEXT__": "CONTEXTO DEL WORKFLOW DE IA",
    "__L_COPY_FULL__": "Copia completa",
    "__L_COPY_API__": "Solo firma de API",
    "__L_COPY_LLM__": "📋 Copiar prompt",
    "__L_OVERVIEW_TITLE__": "PANORAMA DEL PROYECTO",
    "__L_TOTAL_SCRIPTS__": "TOTAL DE SCRIPTS ANALIZADOS",
    "__L_TOTAL_GODS__": "GOD OBJECTS",
    "__L_TOTAL_DEBT__": "DEUDA TÉCNICA",
    "__L_STABILITY_DIST__": "DISTRIBUCIÓN DE ESTABILIDAD",
    "__L_NONE__": "Ninguno",
    "__L_COPIED__": "✅ Copiado",
    "__L_NO_SUPERIORS__": "No se detectaron superiores. El nodo es independiente.",
    "__L_AI_RISK_LOW__": "Riesgo de alucinación IA: BAJO (Estructura clara)",
    "__L_AI_RISK_MED__": "Riesgo de alucinación IA: MEDIO (Saturación lineal)",
    "__L_AI_RISK_HIGH__": "Riesgo de alucinación IA: ALTO (Sobrecarga de contexto)",
    "__L_CLOSE__": "Cerrar",
    "__L_SCENE_DENSITY__": "DENSIDAD DE INSTANCIAS",
    "__L_INSTANCES_FOUND__": "Instancias encontradas:",
    "__L_EXPENSIVE_METHODS__": "MÉTODOS ONEROSOS",
    "__L_CONTEXT_MODE__": "Configuración de contexto LLM",
    "__L_MODE_MAP__": "Solo mapa de API / métodos",
    "__L_MODE_TARGET__": "Objetivo completo",
    "__L_MODE_FULL__": "Código completo",
    "__L_NO_DESCRIPTION__": "Descripción no generada mediante IA.",
    "__L_TOKENS__": "Tokens estimados: ~",
    "__L_FEAT_TITLE_A1__": "ARQUITECTURA Y ANÁLISIS DE IMPACTO",
    "__L_FEAT_MAP_T__": "Mapeo semántico de 5 niveles",
    "__L_FEAT_MAP_D__": "Categoriza automáticamente los scripts en la interfaz visual según su rol estructural en el proyecto.",
    "__L_FEAT_IMPACT_T__": "Análisis de impacto predictivo",
    "__L_FEAT_IMPACT_D__": "Rastrea los enlaces superiores entrantes para ver qué scripts corren riesgo de romperse antes de modificar métodos públicos.",
    "__L_FEAT_GOD_T__": "Detección de God Object",
    "__L_FEAT_GOD_D__": "Aísla instantáneamente las clases con acoplamiento crítico mediante bordes resaltados para encontrar cuellos de botella arquitectónicos.",
    "__L_FEAT_TITLE_A2__": "INTEGRIDAD DEL PROYECTO Y TELEMETRÍA",
    "__L_FEAT_DEFCON_T__": "Sistema de puntuación DEFCON",
    "__L_FEAT_DEFCON_D__": "Evalúa dinámicamente la estabilidad estructural y los niveles de peligro de cada archivo cruzando datos de acoplamiento y deuda técnica.",
    "__L_FEAT_PERF_T__": "Escáner de rendimiento",
    "__L_FEAT_PERF_D__": "Detecta y señala lógicas intensivas para la CPU, como bucles Update continuos o llamadas GetComponent antes de que caigan los FPS.",
    "__L_FEAT_DENSITY_T__": "Alarma de densidad de escena",
    "__L_FEAT_DENSITY_D__": "Envía alertas visuales si un solo script está sobre-instanciado en escenas o prefabs.",
    "__L_FEAT_DEBT_T__": "Radar de deuda técnica",
    "__L_FEAT_DEBT_D__": "Extrae automáticamente todas las anotaciones TODO o FIXME del código fuente directamente al panel interactivo.",
    "__L_FEAT_FRESH_T__": "Seguimiento de frescura temporal",
    "__L_FEAT_FRESH_D__": "Reduce la opacidad de los nodos que no se han modificado en más de 90 días para identificar áreas legacy al instante.",
    "__L_FEAT_TITLE_A3__": "SUITE DE INTEGRACIÓN DE IA (LISTO PARA LLM)",
    "__L_FEAT_CONTEXT_T__": "Exportador de contexto de IA",
    "__L_FEAT_CONTEXT_D__": "Fusiona el script objetivo con sus dependencias y superiores en un solo prompt formateado con un clic para eliminar alucinaciones.",
    "__L_FEAT_RISK_T__": "Análisis predictivo de riesgo de alucinación",
    "__L_FEAT_RISK_D__": "Monitorea el volumen total de caracteres en tiempo real para advertir si la densidad del prompt corre el riesgo de confundir al modelo.",
    "__L_FEAT_SUM_T__": "Resumen de código con IA",
    "__L_FEAT_SUM_D__": "Genera resúmenes estratégicos integrados utilizando modelos locales (Ollama) o las principales API de nube comerciales."
};