const AtlasLocalization = {
    "__L_SEARCH__": "Rechercher un script...",
    "__L_L0__": "L0: Contrats",
    "__L_L1__": "L1: Données/DNA",
    "__L_L2__": "L2: Systèmes principaux",
    "__L_L3__": "L3: Logique",
    "__L_L4__": "L4: Interface UI",
    "__L_DETAIL_TITLE__": "Détail du script",
    "__L_RESET__": "Réinitialiser la vue",
    "__L_SELECT_NODE__": "Sélectionnez un nœud pour afficher l'analyse d'impact et les données de télémétrie.",
    "__L_STRATEGIC__": "DESCRIPTION STRATÉGIQUE",
    "__L_IMPACT__": "ANALYSE D'IMPACT (SUPÉRIEURS)",
    "__L_SCENE__": "PRÉSENCE EN SCÈNE / HIERARCHIE",
    "__L_DEPS__": "DÉPENDANCES (LECTURES)",
    "__L_SOURCE__": "CODE SOURCE COMPLET",
    "__L_HELP_BTN__": "Centre d'aide",
    "__L_REFRESH_BTN__": "Actualiser les données",
    "__L_TAB_ARCH__": "Architecture",
    "__L_TAB_INTEG__": "Intégrité",
    "__L_TAB_AI__": "Suite IA",
    "__L_TELEMETRY_OVERVIEW__": "APERÇU DE LA TÉLÉMÉTRIE DU PROJET",
    "__L_CRITICAL_MODS__": "MODULES CRITIQUES (DEFCON 3)",
    "__L_FRAGILE_MODS__": "MODULES FRAGILES (DEFCON 2)",
    "__L_GOD_DETECTED__": "GOD OBJECTS DÉTECTÉS",
    "__L_TECH_DEBT__": "DETTE TECHNIQUE (TODO/FIXME)",
    "__L_INTEGRITY_STATUS__": "STATUT D'INTÉGRITÉ",
    "__L_DEFCON_1__": "STABLE (DEFCON 1)",
    "__L_DEFCON_2__": "FRAGILE (DEFCON 2)",
    "__L_DEFCON_3__": "CRITIQUE (DEFCON 3)",
    "__L_GOD_WARN__": "⚠️ AVERTISSEMENT ARCHITECTURAL: GOD OBJECT DÉTECTÉ",
    "__L_HEAVY_WARN__": "⚡ AVERTISSEMENT PERFORMANCE: BOUCLES LOURDES DÉTECTÉES",
    "__L_WORKFLOW_CONTEXT__": "CONTEXTE DU WORKFLOW IA",
    "__L_COPY_FULL__": "Copie complète",
    "__L_COPY_API__": "Signature API uniquement",
    "__L_COPY_LLM__": "📋 Copier le prompt",
    "__L_OVERVIEW_TITLE__": "APERÇU DU PROJET",
    "__L_TOTAL_SCRIPTS__": "TOTAL SCRIPTS ANALYSÉS",
    "__L_TOTAL_GODS__": "GOD OBJECTS",
    "__L_TOTAL_DEBT__": "DETTE TECHNIQUE",
    "__L_STABILITY_DIST__": "DISTRIBUTION DE LA STABILITÉ",
    "__L_NONE__": "Aucun",
    "__L_COPIED__": "✅ Copié",
    "__L_NO_SUPERIORS__": "Aucun supérieur détecté. Le nœud est indépendant.",
    "__L_AI_RISK_LOW__": "Risque d'hallucination IA : FAIBLE (Structure claire)",
    "__L_AI_RISK_MED__": "Risque d'hallucination IA : MOYEN (Saturation linéaire)",
    "__L_AI_RISK_HIGH__": "Risque d'hallucination IA : ÉLEVÉ (Surcharge de contexte)",
    "__L_CLOSE__": "Fermer",
    "__L_SCENE_DENSITY__": "DENSITÉ D'INSTANCES",
    "__L_INSTANCES_FOUND__": "Instances trouvées :",
    "__L_EXPENSIVE_METHODS__": "MÉTHODES ONÉREUSES",
    "__L_CONTEXT_MODE__": "Configuration du contexte LLM",
    "__L_MODE_MAP__": "Carte API / Méthodes uniquement",
    "__L_MODE_TARGET__": "Cible complète",
    "__L_MODE_FULL__": "Code complet",
    "__L_NO_DESCRIPTION__": "Description non générée par IA.",
    "__L_TOKENS__": "Jetons estimés : ~",
    "__L_FEAT_TITLE_A1__": "ARCHITECTURE ET ANALYSE D'IMPACT",
    "__L_FEAT_MAP_T__": "Mappage sémantique à 5 niveaux",
    "__L_FEAT_MAP_D__": "Catégorise automatiquement les scripts dans l'interface visuelle selon leur rôle structurel dans le projet.",
    "__L_FEAT_IMPACT_T__": "Analyse d'impact prédictive",
    "__L_FEAT_IMPACT_D__": "Suivi des liens supérieurs pour identifier les risques de rupture avant de modifier des méthodes publiques.",
    "__L_FEAT_GOD_T__": "Détection God Object",
    "__L_FEAT_GOD_D__": "Isole instantanément les classes fortement couplées via des bordures mises en évidence pour trouver les goulots d'étranglement.",
    "__L_FEAT_TITLE_A2__": "INTÉGRITÉ DU PROJET ET TÉLÉMÉTRIE",
    "__L_FEAT_DEFCON_T__": "Système de score DEFCON",
    "__L_FEAT_DEFCON_D__": "Évalue dynamiquement la stabilité structurelle et les niveaux de risque de chaque fichier.",
    "__L_FEAT_PERF_T__": "Scanner de performance",
    "__L_FEAT_PERF_D__": "Détecte les logiques CPU intensives comme les boucles Update continues ou les appels GetComponent.",
    "__L_FEAT_DENSITY_T__": "Alerte de densité de scène",
    "__L_FEAT_DENSITY_D__": "Affiche des alertes visuelles si un script est trop instancié dans les scènes ou les prefabs.",
    "__L_FEAT_DEBT_T__": "Radar de dette technique",
    "__L_FEAT_DEBT_D__": "Extrait automatiquement toutes les annotations TODO ou FIXME du code source vers le panneau interactif.",
    "__L_FEAT_FRESH_T__": "Suivi de la fraîcheur temporelle",
    "__L_FEAT_FRESH_D__": "Réduit l'opacité des nœuds inchangés depuis 90 jours pour identifier les zones héritées.",
    "__L_FEAT_TITLE_A3__": "SUITE D'INTÉGRATION IA (PRÊT POUR LLM)",
    "__L_FEAT_CONTEXT_T__": "Exportateur de contexte IA",
    "__L_FEAT_CONTEXT_D__": "Fusionne le script cible avec ses dépendances et supérieurs en un seul prompt pour éliminer les hallucinations.",
    "__L_FEAT_RISK_T__": "Analyse prédictive des risques d'hallucination",
    "__L_FEAT_RISK_D__": "Surveille le volume de caractères en temps réel pour avertir si la densité du prompt risque de perturber le modèle.",
    "__L_FEAT_SUM_T__": "Résumé de code par IA",
    "__L_FEAT_SUM_D__": "Génère des résumés stratégiques intégrés via des modèles locaux (Ollama) ou des API cloud."
};