const AtlasLocalization = {
    "__L_SEARCH__": "Cerca script...",
    "__L_L0__": "L0: Contratti",
    "__L_L1__": "L1: Dati/DNA",
    "__L_L2__": "L2: Sistemi Core",
    "__L_L3__": "L3: Logica",
    "__L_L4__": "L4: Interfaccia UI",
    "__L_DETAIL_TITLE__": "Dettaglio Script",
    "__L_RESET__": "Ripristina Vista",
    "__L_SELECT_NODE__": "Seleziona un nodo per visualizzare l'analisi di impatto e i dati di telemetria.",
    "__L_STRATEGIC__": "DESCRIZIONE STRATEGICA",
    "__L_IMPACT__": "ANALISI D'IMPATTO (SUPERIORI)",
    "__L_SCENE__": "PRESENZA NELLA SCENA / GERARCHIA",
    "__L_DEPS__": "DIPENDENZE (LETTURE)",
    "__L_SOURCE__": "CODICE SORGENTE COMPLETO",
    "__L_HELP_BTN__": "Hub Guida",
    "__L_REFRESH_BTN__": "Aggiorna Dati",
    "__L_TAB_ARCH__": "Architettura",
    "__L_TAB_INTEG__": "Integrità",
    "__L_TAB_AI__": "Suite AI",
    "__L_TELEMETRY_OVERVIEW__": "PANORAMICA TELEMETRIA PROGETTO",
    "__L_CRITICAL_MODS__": "MODULI CRITICI (DEFCON 3)",
    "__L_FRAGILE_MODS__": "MODULI FRAGILI (DEFCON 2)",
    "__L_GOD_DETECTED__": "GOD OBJECTS RILEVATI",
    "__L_TECH_DEBT__": "DEBITO TECNICO (TODO/FIXME)",
    "__L_INTEGRITY_STATUS__": "STATO DI INTEGRITÀ",
    "__L_DEFCON_1__": "STABILE (DEFCON 1)",
    "__L_DEFCON_2__": "FRAGILE (DEFCON 2)",
    "__L_DEFCON_3__": "CRITICO (DEFCON 3)",
    "__L_GOD_WARN__": "⚠️ AVVISO ARCHITETTURALE: RILEVATO GOD OBJECT SYSTEM",
    "__L_HEAVY_WARN__": "⚡ AVVISO PERFORMANCE: RILEVATI LOOP PESANTI",
    "__L_WORKFLOW_CONTEXT__": "CONTESTO WORKFLOW AI",
    "__L_COPY_FULL__": "Copia Completa",
    "__L_COPY_API__": "Solo Firma API",
    "__L_COPY_LLM__": "📋 Copia Prompt",
    "__L_OVERVIEW_TITLE__": "PANORAMICA PROGETTO",
    "__L_TOTAL_SCRIPTS__": "TOTALE SCRIPT ANALIZZATI",
    "__L_TOTAL_GODS__": "GOD OBJECTS",
    "__L_TOTAL_DEBT__": "DEBITO TECNICO",
    "__L_STABILITY_DIST__": "DISTRIBUZIONE STABILITÀ",
    "__L_NONE__": "Nessuno",
    "__L_COPIED__": "✅ Copiato",
    "__L_NO_SUPERIORS__": "Nessun superiore rilevato. Il nodo è indipendente.",
    "__L_AI_RISK_LOW__": "Rischio Allucinazione AI: BASSO (Struttura Chiara)",
    "__L_AI_RISK_MED__": "Rischio Allucinazione AI: MEDIO (Saturazione Lineare)",
    "__L_AI_RISK_HIGH__": "Rischio Allucinazione AI: ALTO (Sovraccarico Contesto)",
    "__L_CLOSE__": "Chiudi",
    "__L_SCENE_DENSITY__": "DENSITÀ ISTANZE",
    "__L_INSTANCES_FOUND__": "Istanze trovate:",
    "__L_EXPENSIVE_METHODS__": "METODI ONEROSI",
    "__L_CONTEXT_MODE__": "Configurazione Contesto LLM",
    "__L_MODE_MAP__": "Solo Mappa API / Metodi",
    "__L_MODE_TARGET__": "Target Completo",
    "__L_MODE_FULL__": "Codice Completo",
    "__L_NO_DESCRIPTION__": "Descrizione non generata tramite AI.",
    "__L_TOKENS__": "Token stimati: ~",
    "__L_FEAT_TITLE_A1__": "ARCHITETTURA E ANALISI D'IMPATTO",
    "__L_FEAT_MAP_T__": "Mappatura Semantica a 5 Livelli",
    "__L_FEAT_MAP_D__": "Categorizza automaticamente gli script nell'interfaccia visuale in base al loro ruolo strutturale nel progetto.",
    "__L_FEAT_IMPACT_T__": "Analisi Predittiva d'Impatto",
    "__L_FEAT_IMPACT_D__": "Traccia i link superiori in entrata per vedere quali script rischiano di rompersi prima di modificare i metodi pubblici.",
    "__L_FEAT_GOD_T__": "Rilevamento God Object",
    "__L_FEAT_GOD_D__": "Isola istantaneamente le classi con accoppiamento critico tramite bordi evidenziati per trovare colli di bottiglia architettonici.",
    "__L_FEAT_TITLE_A2__": "INTEGRITÀ DEL PROGETTO E TELEMETRIA",
    "__L_FEAT_DEFCON_T__": "Sistema di Punteggio DEFCON",
    "__L_FEAT_DEFCON_D__": "Valuta dinamicamente la stabilità strutturale e i livelli di pericolo di ogni file incrociando dati di accoppiamento e debito tecnico.",
    "__L_FEAT_PERF_T__": "Scanner Hotspot Performance",
    "__L_FEAT_PERF_D__": "Rileva e segnala logiche CPU-intensive come cicli Update continui o chiamate GetComponent prima che si verifichino cali di framerate.",
    "__L_FEAT_DENSITY_T__": "Allarme Densità Scena",
    "__L_FEAT_DENSITY_D__": "Invia avvisi visivi lampeggianti se un singolo script è sovra-istanziato nelle scene o nei prefab.",
    "__L_FEAT_DEBT_T__": "Radar Debito Tecnico",
    "__L_FEAT_DEBT_D__": "Estrae automaticamente tutte le annotazioni TODO o FIXME e i commenti dal codice sorgente direttamente nel pannello interattivo.",
    "__L_FEAT_FRESH_T__": "Tracciamento Freschezza Temporale",
    "__L_FEAT_FRESH_D__": "Riduce l'opacità dei nodi non modificati da oltre 90 giorni per identificare istantaneamente le aree legacy del codice.",
    "__L_FEAT_TITLE_A3__": "SUITE INTEGRAZIONE AI (LLM READY)",
    "__L_FEAT_CONTEXT_T__": "Esportatore Contesto AI",
    "__L_FEAT_CONTEXT_D__": "Unisce lo script target con le dipendenze correlate e i superiori in un unico prompt formattato con un clic per eliminare le allucinazioni.",
    "__L_FEAT_RISK_T__": "Analisi Predittiva Rischio Allucinazione",
    "__L_FEAT_RISK_D__": "Monitora il volume totale di caratteri accumulati in tempo reale per avvisare se la densità del prompt rischia di confondere il modello.",
    "__L_FEAT_SUM_T__": "Riassunto Codice tramite AI",
    "__L_FEAT_SUM_D__": "Genera riassunti strategici integrati utilizzando modelli offline locali tramite Ollama o le principali API cloud commerciali."
};