const AtlasLocalization = {
    "__L_SEARCH__": "スクリプト検索...",
    "__L_L0__": "L0: 契約",
    "__L_L1__": "L1: データ/DNA",
    "__L_L2__": "L2: コアシステム",
    "__L_L3__": "L3: ロジック",
    "__L_L4__": "L4: UIインターフェース",
    "__L_DETAIL_TITLE__": "スクリプト詳細",
    "__L_RESET__": "表示をリセット",
    "__L_SELECT_NODE__": "ノードを選択して影響分析とテレメトリデータを表示します。",
    "__L_STRATEGIC__": "戦略的説明",
    "__L_IMPACT__": "影響分析 (上位ノード)",
    "__L_SCENE__": "シーンの存在 / 階層",
    "__L_DEPS__": "依存関係 (読み取り)",
    "__L_SOURCE__": "完全なソースコード",
    "__L_HELP_BTN__": "ガイドハブ",
    "__L_REFRESH_BTN__": "データを更新",
    "__L_TAB_ARCH__": "アーキテクチャ",
    "__L_TAB_INTEG__": "整合性",
    "__L_TAB_AI__": "AIスイート",
    "__L_TELEMETRY_OVERVIEW__": "プロジェクトテレメトリ概要",
    "__L_CRITICAL_MODS__": "クリティカルモジュール (DEFCON 3)",
    "__L_FRAGILE_MODS__": "脆弱なモジュール (DEFCON 2)",
    "__L_GOD_DETECTED__": "God Object を検出",
    "__L_TECH_DEBT__": "技術的負債 (TODO/FIXME)",
    "__L_INTEGRITY_STATUS__": "整合性ステータス",
    "__L_DEFCON_1__": "安定 (DEFCON 1)",
    "__L_DEFCON_2__": "脆弱 (DEFCON 2)",
    "__L_DEFCON_3__": "危険 (DEFCON 3)",
    "__L_GOD_WARN__": "⚠️ アーキテクチャ警告: God Object システムを検出",
    "__L_HEAVY_WARN__": "⚡ パフォーマンス警告: 重いメソッドループを検出",
    "__L_WORKFLOW_CONTEXT__": "AIワークフローコンテキスト",
    "__L_COPY_FULL__": "フルコピー",
    "__L_COPY_API__": "APIシグネチャのみ",
    "__L_COPY_LLM__": "📋 プロンプトをコピー",
    "__L_OVERVIEW_TITLE__": "プロジェクト概要",
    "__L_TOTAL_SCRIPTS__": "解析済みスクリプト合計",
    "__L_TOTAL_GODS__": "God Object 合計",
    "__L_TOTAL_DEBT__": "技術的負債合計",
    "__L_STABILITY_DIST__": "安定性分布",
    "__L_NONE__": "なし",
    "__L_COPIED__": "✅ コピーしました",
    "__L_NO_SUPERIORS__": "上位ノードは検出されませんでした。ノードは独立しています。",
    "__L_AI_RISK_LOW__": "AIハルシネーションリスク: 低 (構造が明確)",
    "__L_AI_RISK_MED__": "AIハルシネーションリスク: 中 (線形飽和)",
    "__L_AI_RISK_HIGH__": "AIハルシネーションリスク: 高 (コンテキスト過負荷)",
    "__L_CLOSE__": "閉じる",
    "__L_SCENE_DENSITY__": "インスタンス密度",
    "__L_INSTANCES_FOUND__": "見つかったインスタンス:",
    "__L_EXPENSIVE_METHODS__": "負荷の高いメソッド",
    "__L_CONTEXT_MODE__": "LLMコンテキスト設定",
    "__L_MODE_MAP__": "API/メソッドマップのみ",
    "__L_MODE_TARGET__": "ターゲット全体",
    "__L_MODE_FULL__": "完全なコード",
    "__L_NO_DESCRIPTION__": "AIによって生成された説明はありません。",
    "__L_TOKENS__": "推定トークン数: ~",
    "__L_FEAT_TITLE_A1__": "アーキテクチャと影響分析",
    "__L_FEAT_MAP_T__": "5段階セマンティックマッピング",
    "__L_FEAT_MAP_D__": "プロジェクト内の構造的な役割に基づいて、視覚インターフェース上のスクリプトを自動分類します。",
    "__L_FEAT_IMPACT_T__": "予測的影響分析",
    "__L_FEAT_IMPACT_D__": "上位ノードへのリンクを追跡し、パブリックメソッドを修正する前にどのスクリプトが破損するリスクがあるかを確認します。",
    "__L_FEAT_GOD_T__": "God Object 検出",
    "__L_FEAT_GOD_D__": "重要な結合を持つクラスを即座に分離し、枠を強調表示してアーキテクチャのボトルネックを見つけます。",
    "__L_FEAT_TITLE_A2__": "プロジェクトの整合性とテレメトリ",
    "__L_FEAT_DEFCON_T__": "DEFCONスコアシステム",
    "__L_FEAT_DEFCON_D__": "結合データと技術的負債を照合し、各ファイルの構造的安定性と危険度を動的に評価します。",
    "__L_FEAT_PERF_T__": "パフォーマンスホットスキャナー",
    "__L_FEAT_PERF_D__": "フレームレートが低下する前に、継続的なUpdateループやGetComponent呼び出しなどのCPU負荷の高いロジックを検出・警告します。",
    "__L_FEAT_DENSITY_T__": "シーン密度アラーム",
    "__L_FEAT_DENSITY_D__": "シーンやプレハブ内で単一のスクリプトアセットが過剰にインスタンス化されている場合、点滅する視覚アラートを送信します。",
    "__L_FEAT_DEBT_T__": "技術的負債レーダー",
    "__L_FEAT_DEBT_D__": "ソースコード内のすべてのTODOまたはFIXMEアノテーションを自動的に抽出し、インタラクティブパネルに表示します。",
    "__L_FEAT_FRESH_T__": "時間的鮮度トラッキング",
    "__L_FEAT_FREAT_D__": "90日間変更されていないノードの不透明度を下げ、レガシーなコード領域を即座に特定します。",
    "__L_FEAT_TITLE_A3__": "AI統合スイート (LLM対応)",
    "__L_FEAT_CONTEXT_T__": "AIコンテキストエクスポート",
    "__L_FEAT_CONTEXT_D__": "対象スクリプト、関連する依存関係、上位ノードをワンクリックで単一のフォーマット済みプロンプトに統合し、ハルシネーションを排除します。",
    "__L_FEAT_RISK_T__": "ハルシネーションリスク予測分析",
    "__L_FEAT_RISK_D__": "リアルタイムで累積文字数を監視し、プロンプト密度がモデルを混乱させるリスクがある場合に警告します。",
    "__L_FEAT_SUM_T__": "AIコード要約",
    "__L_FEAT_SUM_D__": "ローカルモデル (Ollama) または主要な商用クラウドAPIを使用して、統合的な戦略的要約を生成します。"
};