const AtlasLocalization = {
    "__L_SEARCH__": "搜索脚本...",
    "__L_L0__": "L0: 合约",
    "__L_L1__": "L1: 数据/DNA",
    "__L_L2__": "L2: 核心系统",
    "__L_L3__": "L3: 逻辑",
    "__L_L4__": "L4: UI 界面",
    "__L_DETAIL_TITLE__": "脚本详情",
    "__L_RESET__": "重置视图",
    "__L_SELECT_NODE__": "选择一个节点以查看影响分析和遥测数据。",
    "__L_STRATEGIC__": "战略描述",
    "__L_IMPACT__": "影响分析 (上级节点)",
    "__L_SCENE__": "场景存在 / 层级",
    "__L_DEPS__": "依赖关系 (读取)",
    "__L_SOURCE__": "完整源代码",
    "__L_HELP_BTN__": "指南中心",
    "__L_REFRESH_BTN__": "刷新数据",
    "__L_TAB_ARCH__": "架构",
    "__L_TAB_INTEG__": "完整性",
    "__L_TAB_AI__": "AI 套件",
    "__L_TELEMETRY_OVERVIEW__": "项目遥测概览",
    "__L_CRITICAL_MODS__": "关键模块 (DEFCON 3)",
    "__L_FRAGILE_MODS__": "脆弱模块 (DEFCON 2)",
    "__L_GOD_DETECTED__": "检测到 God Objects",
    "__L_TECH_DEBT__": "技术债务 (TODO/FIXME)",
    "__L_INTEGRITY_STATUS__": "完整性状态",
    "__L_DEFCON_1__": "稳定 (DEFCON 1)",
    "__L_DEFCON_2__": "脆弱 (DEFCON 2)",
    "__L_DEFCON_3__": "严重 (DEFCON 3)",
    "__L_GOD_WARN__": "⚠️ 架构警告: 检测到 God Object 系统",
    "__L_HEAVY_WARN__": "⚡ 性能警告: 发现繁重的循环方法",
    "__L_WORKFLOW_CONTEXT__": "AI 工作流上下文",
    "__L_COPY_FULL__": "完整复制",
    "__L_COPY_API__": "仅 API 签名",
    "__L_COPY_LLM__": "📋 复制提示词",
    "__L_OVERVIEW_TITLE__": "项目概览",
    "__L_TOTAL_SCRIPTS__": "已解析脚本总数",
    "__L_TOTAL_GODS__": "God Objects 总数",
    "__L_TOTAL_DEBT__": "技术债务总数",
    "__L_STABILITY_DIST__": "稳定性分布",
    "__L_NONE__": "无",
    "__L_COPIED__": "✅ 已复制",
    "__L_NO_SUPERIORS__": "未检测到上级节点。该节点是独立的。",
    "__L_AI_RISK_LOW__": "AI 幻觉风险: 低 (结构清晰)",
    "__L_AI_RISK_MED__": "AI 幻觉风险: 中 (线性饱和)",
    "__L_AI_RISK_HIGH__": "AI 幻觉风险: 高 (上下文过载)",
    "__L_CLOSE__": "关闭",
    "__L_SCENE_DENSITY__": "实例密度",
    "__L_INSTANCES_FOUND__": "找到的实例数:",
    "__L_EXPENSIVE_METHODS__": "昂贵的方法",
    "__L_CONTEXT_MODE__": "LLM 上下文配置",
    "__L_MODE_MAP__": "仅 API / 方法映射",
    "__L_MODE_TARGET__": "完整目标",
    "__L_MODE_FULL__": "完整代码",
    "__L_NO_DESCRIPTION__": "未由 AI 生成描述。",
    "__L_TOKENS__": "预估 Token 数: ~",
    "__L_FEAT_TITLE_A1__": "架构与影响分析",
    "__L_FEAT_MAP_T__": "5 层语义映射",
    "__L_FEAT_MAP_D__": "根据脚本在项目中的结构角色，在可视化界面中自动分类脚本。",
    "__L_FEAT_IMPACT_T__": "预测性影响分析",
    "__L_FEAT_IMPACT_D__": "跟踪传入的上级链接，以查看在修改公共方法之前哪些脚本有损坏风险。",
    "__L_FEAT_GOD_T__": "God Object 检测",
    "__L_FEAT_GOD_D__": "通过高亮边框立即隔离具有关键耦合的类，以发现架构瓶颈。",
    "__L_FEAT_TITLE_A2__": "项目完整性与遥测",
    "__L_FEAT_DEFCON_T__": "DEFCON 评分系统",
    "__L_FEAT_DEFCON_D__": "通过交叉引用耦合数据和技术债务，动态评估每个文件的结构稳定性和危险级别。",
    "__L_FEAT_PERF_T__": "性能热点扫描器",
    "__L_FEAT_PERF_D__": "在帧率下降之前检测并标记 CPU 密集型逻辑，例如持续的 Update 循环或 GetComponent 调用。",
    "__L_FEAT_DENSITY_T__": "场景密度报警",
    "__L_FEAT_DENSITY_D__": "如果单个脚本资源在场景或预制件中被过度实例化，则发送闪烁的视觉警报。",
    "__L_FEAT_DEBT_T__": "技术债务雷达",
    "__L_FEAT_DEBT_D__": "自动从源代码中提取所有 TODO 或 FIXME 注释，并直接显示在交互式面板中。",
    "__L_FEAT_FRESH_T__": "时间新鲜度跟踪",
    "__L_FEAT_FRESH_D__": "降低超过 90 天未修改节点的透明度，以立即识别旧代码区域。",
    "__L_FEAT_TITLE_A3__": "AI 集成套件 (LLM 就绪)",
    "__L_FEAT_CONTEXT_T__": "AI 上下文导出器",
    "__L_FEAT_CONTEXT_D__": "一键将目标脚本与相关的依赖项和上级节点合并为单个格式化的提示词，以消除幻觉。",
    "__L_FEAT_RISK_T__": "AI 幻觉风险预测分析",
    "__L_FEAT_RISK_D__": "实时监控累计字符总量，以警告提示词密度是否可能导致模型混淆。",
    "__L_FEAT_SUM_T__": "AI 代码摘要",
    "__L_FEAT_SUM_D__": "使用本地模型 (Ollama) 或主流商业云 API 生成集成的战略摘要。"
};